import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <Script
            src="https://clerk.teller.co.za/npm/@clerk/ui@1/dist/ui.browser.js"
            strategy="afterInteractive"
            crossOrigin="anonymous"
          />

          <Script
            src="https://clerk.teller.co.za/npm/@clerk/clerk-js@6/dist/clerk.browser.js"
            strategy="afterInteractive"
            crossOrigin="anonymous"
            data-clerk-publishable-key="pk_live_Y2xlcmsudGVsbGVyLmNvLnphJA"
          />

          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
